/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poodemo.ejercicio4;

/**
 *
 * @author USER
 */
public class Ejercicio04 extends javax.swing.JFrame {
    private static final int ANCHO = 800, ALTO = 500, TAM_PATO = 240;

    private final Pato pato = new Pato("Donald");
    private final Volador volador = pato;   // polimorfismo
    private final Nadador nadador = pato;

    private java.awt.image.BufferedImage fondoVolar, fondoNadar;
    private final java.awt.image.BufferedImage[] framesVolar = new java.awt.image.BufferedImage[2];
    private final java.awt.image.BufferedImage[] framesNadar = new java.awt.image.BufferedImage[2];

    private double posX = 100, dir = 1;
    private int frame = 0, tick = 0;

    private java.awt.image.BufferedImage leer(String nombre) throws java.io.IOException {
        java.net.URL url = getClass().getResource("/img/" + nombre);
        if (url == null) throw new java.io.IOException("No se encontró /img/" + nombre);
        return javax.imageio.ImageIO.read(url);
    }

    private void cargarImagenes() {
        try {
            fondoVolar = leer("fondo_volar.png");
            fondoNadar = leer("fondo_nadar.png");
            framesVolar[0] = leer("pato_volar_1.png");
            framesVolar[1] = leer("pato_volar_2.png");
            framesNadar[0] = leer("pato_nadar_1.png");
            framesNadar[1] = leer("pato_nadar_2.png");
        } catch (java.io.IOException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage());
            System.exit(1);
        }
    }

    private void actualizar() {
        boolean vuela = pato.getEstado() == Pato.Estado.VOLANDO;
        posX += (vuela ? 5 : 2) * dir;
        if (vuela) {
            if (posX > ANCHO) posX = -TAM_PATO;
        } else {
            if (posX > ANCHO - TAM_PATO) dir = -1;
            if (posX < 0) dir = 1;
        }
        tick++;
        if (tick % (vuela ? 4 : 10) == 0) frame = (frame + 1) % 2;
        panelEscena.repaint();
    }

    private class PanelEscena extends javax.swing.JPanel {
        PanelEscena() { setPreferredSize(new java.awt.Dimension(ANCHO, ALTO)); }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g;
            g2.setRenderingHint(java.awt.RenderingHints.KEY_INTERPOLATION,
                    java.awt.RenderingHints.VALUE_INTERPOLATION_NEAREST_NEIGHBOR);
            boolean vuela = pato.getEstado() == Pato.Estado.VOLANDO;
            g2.drawImage(vuela ? fondoVolar : fondoNadar, 0, 0, ANCHO, ALTO, null);

            java.awt.image.BufferedImage img = (vuela ? framesVolar : framesNadar)[frame];
            int px = (int) posX;
            int py = vuela ? 110 + (int) (Math.sin(tick / 6.0) * 25) : 250;
            if (dir >= 0) g2.drawImage(img, px, py, TAM_PATO, TAM_PATO, null);
            else g2.drawImage(img, px + TAM_PATO, py, -TAM_PATO, TAM_PATO, null);
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio04.class.getName());

    /**
     * Creates new form Ejercicio04
     */
    public Ejercicio04() {
        initComponents();
        cargarImagenes();
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
        lblMensaje.setText(nadador.nadar());
        new javax.swing.Timer(33, e -> actualizar()).start();   // ~30 FPS
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscena = new PanelEscena();
        jPanel3 = new javax.swing.JPanel();
        btnVolar = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnNadar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelEscenaLayout = new javax.swing.GroupLayout(panelEscena);
        panelEscena.setLayout(panelEscenaLayout);
        panelEscenaLayout.setHorizontalGroup(
            panelEscenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
        );
        panelEscenaLayout.setVerticalGroup(
            panelEscenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        getContentPane().add(panelEscena, java.awt.BorderLayout.CENTER);

        btnVolar.setText("VOLAR");
        btnVolar.addActionListener(this::btnVolarActionPerformed);
        jPanel3.add(btnVolar);

        lblMensaje.setText("jLabel1");
        jPanel3.add(lblMensaje);

        btnNadar.setText("NADAR");
        btnNadar.addActionListener(this::btnNadarActionPerformed);
        jPanel3.add(btnNadar);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolarActionPerformed
        lblMensaje.setText(volador.volar());
        posX = 100; dir = 1;
    }//GEN-LAST:event_btnVolarActionPerformed

    private void btnNadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNadarActionPerformed
        lblMensaje.setText(nadador.nadar());
        posX = 100; dir = 1;
    }//GEN-LAST:event_btnNadarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ejercicio04().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNadar;
    private javax.swing.JButton btnVolar;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel panelEscena;
    // End of variables declaration//GEN-END:variables
}
