/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poodemo.Ejercicio3.src.ejercicio3;

/**
 *
 * @author MAYERHOFFER
 */
public class ElectrodomesticosFrm extends javax.swing.JFrame {
    Televisor tv = new Televisor();
    Refrigerador refri = new Refrigerador();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ElectrodomesticosFrm.class.getName());

    /**
     * Creates new form ElectrodomesticosFrm
     */
    public ElectrodomesticosFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTlvon = new javax.swing.JButton();
        btnTlvof = new javax.swing.JButton();
        btnRfron = new javax.swing.JButton();
        btnRfrof = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblEstadoTV = new javax.swing.JLabel();
        lblEstadoRefri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Control de electrodomésticos");

        jLabel2.setText("Televisor");

        jLabel3.setText("Refrigeradora");

        btnTlvon.setText("Encender");
        btnTlvon.addActionListener(this::btnTlvonActionPerformed);

        btnTlvof.setText("Apagar");
        btnTlvof.addActionListener(this::btnTlvofActionPerformed);

        btnRfron.setText("Encender");
        btnRfron.addActionListener(this::btnRfronActionPerformed);

        btnRfrof.setText("Apagar");
        btnRfrof.addActionListener(this::btnRfrofActionPerformed);

        jLabel4.setText("Estado");

        lblEstadoTV.setText("Apagado");

        lblEstadoRefri.setText("Apagado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblEstadoTV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstadoRefri)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTlvon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTlvof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRfron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRfrof, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRfron)
                    .addComponent(btnTlvon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRfrof)
                    .addComponent(btnTlvof))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoTV)
                    .addComponent(lblEstadoRefri))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTlvonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTlvonActionPerformed
tv.encender();
lblEstadoTV.setText(tv.isEncendido() ? "Encendido" : "Apagado");   // TODO add your handling code here:
    }//GEN-LAST:event_btnTlvonActionPerformed

    private void btnTlvofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTlvofActionPerformed
tv.apagar();
lblEstadoTV.setText(tv.isEncendido() ? "Encendido" : "Apagado");        // TODO add your handling code here:
    }//GEN-LAST:event_btnTlvofActionPerformed

    private void btnRfronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfronActionPerformed
refri.encender();
lblEstadoRefri.setText(refri.isEncendido() ? "Encendido" : "Apagado");        // TODO add your handling code here:
    }//GEN-LAST:event_btnRfronActionPerformed

    private void btnRfrofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRfrofActionPerformed
refri.apagar();
lblEstadoRefri.setText(refri.isEncendido() ? "Encendido" : "Apagado");        // TODO add your handling code here:
    }//GEN-LAST:event_btnRfrofActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ElectrodomesticosFrm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRfrof;
    private javax.swing.JButton btnRfron;
    private javax.swing.JButton btnTlvof;
    private javax.swing.JButton btnTlvon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEstadoRefri;
    private javax.swing.JLabel lblEstadoTV;
    // End of variables declaration//GEN-END:variables
}
