/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poodemo.ejercicio1;

import com.mycompany.poodemo.ejercicio1.modelo.*;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * @author frank
 */
public class VentanaCirculo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCirculo.class.getName());

    // Modelo para la tabla de registros del círculo
    private DefaultTableModel modeloTablaCirculo;

    // Instancia del panel de dibujo dinámico e interactivo
    private PanelCanvasCirculo canvasCirculo;

    /**
     * Creates new form VentanaCirculo
     */
    public VentanaCirculo() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla

        // Inicializar las columnas de la tabla de historial del círculo
        modeloTablaCirculo = new DefaultTableModel(new String[]{"Radio", "Unidad", "Área Final", "Paso a Paso"}, 0);
        tblCirculo.setModel(modeloTablaCirculo);

        // Ajustar el ancho de las columnas
        tblCirculo.getColumnModel().getColumn(0).setPreferredWidth(80);  // Radio
        tblCirculo.getColumnModel().getColumn(1).setPreferredWidth(130); // Unidad
        tblCirculo.getColumnModel().getColumn(2).setPreferredWidth(150); // Área Final
        tblCirculo.getColumnModel().getColumn(3).setPreferredWidth(280); // Paso a Paso

        // Deshabilitar el combo de destino por defecto
        jComboBoxDestino.setEnabled(false);

        // Configurar e integrar el panel gráfico interactivo dentro del panel de NetBeans
        canvasCirculo = new PanelCanvasCirculo();
        canvasCirculo.setBackground(Color.WHITE);

        // Listener para sincronizar el arrastre del mouse y el guardado en la tabla al soltar
        canvasCirculo.setOnRadioChangeListener(new PanelCanvasCirculo.RadioChangeListener() {
            @Override
            public void onRadioChanged(double nuevoRadio) {
                txtRadio.setText(String.valueOf(nuevoRadio));
                actualizarCalculoEnVivo(nuevoRadio);
            }

            @Override
            public void onArrastreFinalizado() {
                // Guarda en la tabla del historial únicamente cuando el usuario suelta el mouse
                btnCalcularCirculo.doClick();
            }
        });

        panelGrafico.setLayout(new java.awt.BorderLayout());
        panelGrafico.add(canvasCirculo, java.awt.BorderLayout.CENTER);
    }

    /**
     * Método auxiliar para calcular y mostrar en tiempo real en la interfaz sin saturar la tabla
     */
    private void actualizarCalculoEnVivo(double radio) {
        try {
            String unidadIngreso = jComboBox1.getSelectedItem().toString();
            Circulo circulo = new Circulo(radio, unidadIngreso);
            double areaFinal;
            String unidadFinal;

            if (tglConvertir.isSelected()) {
                String unidadDestino = jComboBoxDestino.getSelectedItem().toString();
                areaFinal = circulo.convertirAreaA(unidadDestino);
                unidadFinal = unidadDestino;
            } else {
                areaFinal = circulo.calcularArea();
                unidadFinal = unidadIngreso;
            }

            lblResultadoCirculo.setText(String.format("Área: %.4f %s²", areaFinal, unidadFinal));

            canvasCirculo.setRadio(radio);
            String unidadDestinoStr = tglConvertir.isSelected() ? jComboBoxDestino.getSelectedItem().toString() : "";
            canvasCirculo.setResultadoInfo(areaFinal, unidadFinal, tglConvertir.isSelected(), unidadIngreso, unidadDestinoStr);
        } catch (Exception e) {
            // Ignorar errores menores durante el movimiento fluido del mouse
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRadio = new javax.swing.JTextField();
        btnCalcularCirculo = new javax.swing.JButton();
        lblResultadoCirculo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCirculo = new javax.swing.JTable();
        btnVolverMenu = new javax.swing.JButton();
        btnLimpiarTabla = new javax.swing.JButton();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        tglConvertir = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("\"Cálculo del Círculo\"");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("\"Radio:\"");

        txtRadio.addActionListener(this::txtRadioActionPerformed);

        btnCalcularCirculo.setText("Calcular Círculo");
        btnCalcularCirculo.addActionListener(this::btnCalcularCirculoActionPerformed);

        lblResultadoCirculo.setText("Resultado Círculo:");

        tblCirculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCirculo);

        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.addActionListener(this::btnVolverMenuActionPerformed);

        btnLimpiarTabla.setText("Limpiar Historial");
        btnLimpiarTabla.addActionListener(this::btnLimpiarTablaActionPerformed);

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milímetros (mm)", "Centímetros (cm)", "Decímetros (dm)", "Metros (m)", "Kilómetros (km)" }));
        jComboBoxDestino.addActionListener(this::jComboBoxDestinoActionPerformed);

        tglConvertir.setText("Habilitar Conversión");
        tglConvertir.addActionListener(this::tglConvertirActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milímetros (mm)", "Centímetros (cm)", "Decímetros (dm)", "Metros (m)", "Kilómetros (km)" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        panelGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGrafico.setPreferredSize(new java.awt.Dimension(250, 100));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblResultadoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVolverMenu)
                        .addGap(59, 59, 59)
                        .addComponent(btnLimpiarTabla))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btnCalcularCirculo))
                                        .addGap(289, 289, 289))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tglConvertir)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglConvertir)
                            .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnCalcularCirculo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverMenu)
                    .addComponent(btnLimpiarTabla))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCirculoActionPerformed
        try {
            if (txtRadio.getText().trim().isEmpty()) {
                throw new IllegalArgumentException("El campo del radio no puede estar vacío.");
            }

            double radio = Double.parseDouble(txtRadio.getText().trim());

            if (radio <= 0) {
                throw new ArithmeticException("El radio debe ser mayor a 0.");
            }

            String unidadIngreso = jComboBox1.getSelectedItem().toString();
            Circulo circulo = new Circulo(radio, unidadIngreso);

            double areaFinal;
            String unidadFinal;
            String pasoAPaso;

            if (tglConvertir.isSelected()) {
                String unidadDestino = jComboBoxDestino.getSelectedItem().toString();
                areaFinal = circulo.convertirAreaA(unidadDestino);
                unidadFinal = unidadDestino;

                double radioConvertido = radio * obtenerFactorPrueba(unidadIngreso) / obtenerFactorPrueba(unidadDestino);
                pasoAPaso = String.format("Conv. (%.1f %s a %s) -> π × (%.2f)² = %.4f",
                        radio, unidadIngreso, unidadDestino, radioConvertido, areaFinal);
            } else {
                areaFinal = circulo.calcularArea();
                unidadFinal = unidadIngreso;
                pasoAPaso = String.format("π × (%.2f)² = %.4f", radio, areaFinal);
            }

            lblResultadoCirculo.setText(String.format("Área: %.4f %s²", areaFinal, unidadFinal));

            // Añade al historial de la tabla una sola vez
            modeloTablaCirculo.addRow(new Object[]{radio, unidadIngreso, String.format("%.4f %s²", areaFinal, unidadFinal), pasoAPaso});

            canvasCirculo.setRadio(radio);
            String unidadDestinoStr = tglConvertir.isSelected() ? jComboBoxDestino.getSelectedItem().toString() : "";
            canvasCirculo.setResultadoInfo(areaFinal, unidadFinal, tglConvertir.isSelected(), unidadIngreso, unidadDestinoStr);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese solo un valor numérico válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularCirculoActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        VentanaPrincipio menu = new VentanaPrincipio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        modeloTablaCirculo.setRowCount(0);
        lblResultadoCirculo.setText("Resultado Círculo:");
    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            if (!txtRadio.getText().trim().isEmpty()) {
                double radio = Double.parseDouble(txtRadio.getText().trim());
                actualizarCalculoEnVivo(radio);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void tglConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglConvertirActionPerformed
        jComboBoxDestino.setEnabled(tglConvertir.isSelected());
        try {
            if (!txtRadio.getText().trim().isEmpty()) {
                double radio = Double.parseDouble(txtRadio.getText().trim());
                actualizarCalculoEnVivo(radio);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_tglConvertirActionPerformed

    private void jComboBoxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDestinoActionPerformed
        try {
            if (!txtRadio.getText().trim().isEmpty()) {
                double radio = Double.parseDouble(txtRadio.getText().trim());
                actualizarCalculoEnVivo(radio);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_jComboBoxDestinoActionPerformed

    private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRadioActionPerformed
        btnCalcularCirculo.doClick();
    }//GEN-LAST:event_txtRadioActionPerformed

    // Método auxiliar para obtener el factor de conversión respecto a los metros (o unidad base)
    private double obtenerFactorPrueba(String unidad) {
        if (unidad.contains("Milímetros")) return 0.001;
        if (unidad.contains("Centímetros")) return 0.01;
        if (unidad.contains("Decímetros")) return 0.1;
        if (unidad.contains("Metros")) return 1.0;
        if (unidad.contains("Kilómetros")) return 1000.0;
        return 1.0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaCirculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCirculo;
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultadoCirculo;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTable tblCirculo;
    private javax.swing.JToggleButton tglConvertir;
    private javax.swing.JTextField txtRadio;
    // End of variables declaration//GEN-END:variables
}

// =====================================================================
// CLASE AUXILIAR: PANEL GRÁFICO INTERACTIVO (ESTILO GEOGEBRA LIBRE)
// =====================================================================
class PanelCanvasCirculo extends JPanel implements java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
    private double radio = 0;
    private double anguloRadianes = 0; // Permite rotación libre del punto rojo
    private String textoResultado = "";

    public interface RadioChangeListener {
        void onRadioChanged(double nuevoRadio);
        void onArrastreFinalizado(); // Se dispara únicamente al soltar el mouse
    }

    private RadioChangeListener listener;

    public void setOnRadioChangeListener(RadioChangeListener listener) {
        this.listener = listener;
    }

    public PanelCanvasCirculo() {
        addMouseListener(this);
        addMouseMotionListener(this);
    }

    public void setRadio(double radio) {
        this.radio = radio;
        repaint();
    }

    public void setResultadoInfo(double area, String unidadFinal, boolean esConvertido, String unidadIngreso, String unidadDestino) {
        if (esConvertido) {
            this.textoResultado = String.format("Área: %.4f %s² (Conv: %s ➔ %s)", area, unidadFinal, unidadIngreso, unidadDestino);
        } else {
            this.textoResultado = String.format("Área: %.4f %s² (Sin conversión)", area, unidadFinal);
        }
        repaint();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);

        java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
        g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        int ancho = getWidth();
        int alto = getHeight();
        int centroX = ancho / 2;
        int centroY = alto / 2;

        if (radio <= 0) {
            g2d.setColor(Color.GRAY);
            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 12));
            g2d.drawString("Haz clic y arrastra el punto rojo para mover el radio...", 15, 30);
            return;
        }

        double escala = 20.0;
        int radioPixeles = (int) (radio * escala);

        int maxRadioPermitido = Math.min(centroX, centroY) - 35;
        if (radioPixeles > maxRadioPermitido && maxRadioPermitido > 0) {
            radioPixeles = maxRadioPermitido;
        } else if (radioPixeles < 15 && radio > 0) {
            radioPixeles = 30;
        }

        // 1. Relleno del círculo (Celeste claro estilo GeoGebra)
        g2d.setColor(new Color(230, 240, 255));
        g2d.fillOval(centroX - radioPixeles, centroY - radioPixeles, radioPixeles * 2, radioPixeles * 2);

        // 2. Borde del círculo
        g2d.setColor(new Color(50, 100, 220));
        g2d.setStroke(new java.awt.BasicStroke(2));
        g2d.drawOval(centroX - radioPixeles, centroY - radioPixeles, radioPixeles * 2, radioPixeles * 2);

        // 3. Punto central (A)
        g2d.setColor(Color.BLACK);
        g2d.fillOval(centroX - 4, centroY - 4, 8, 8);
        g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        g2d.drawString("A", centroX - 15, centroY + 20);

        // 4. Coordenadas del punto extremo del radio usando trigonometría (rotación libre)
        int puntoX = (int) (centroX + radioPixeles * Math.cos(anguloRadianes));
        int puntoY = (int) (centroY + radioPixeles * Math.sin(anguloRadianes));

        // 5. Línea del radio dinámica
        g2d.setColor(new Color(50, 100, 220));
        g2d.drawLine(centroX, centroY, puntoX, puntoY);

        // 6. Punto rojo interactivo en el extremo del radio
        g2d.setColor(new Color(220, 50, 50));
        g2d.fillOval(puntoX - 6, puntoY - 6, 12, 12);

        // 7. Texto del radio dinámico cerca de la línea
        g2d.setColor(new Color(0, 50, 150));
        g2d.drawString("r = " + String.format("%.2f", radio), centroX + ((puntoX - centroX) / 2) - 15, centroY + ((puntoY - centroY) / 2) - 8);

        // 8. Letra "P" en el perímetro
        g2d.drawString("P", puntoX + 8, puntoY + 8);

        // 9. Mostrar el resultado y estado de conversión dentro de la imagen
        if (!textoResultado.isEmpty()) {
            g2d.setColor(new Color(20, 20, 20));
            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
            g2d.drawString(textoResultado, 15, 25);
        }
    }

    @Override
    public void mousePressed(java.awt.event.MouseEvent e) {
        actualizarRadioYAnguloDesdeMouse(e.getX(), e.getY(), false);
    }

    @Override
    public void mouseDragged(java.awt.event.MouseEvent e) {
        // Actualiza el dibujo y la etiqueta superior de forma fluida sin saturar el historial
        actualizarRadioYAnguloDesdeMouse(e.getX(), e.getY(), false);
    }

    @Override
    public void mouseReleased(java.awt.event.MouseEvent e) {
        // Al soltar el mouse, registra el cálculo final una sola vez en la tabla de historial
        actualizarRadioYAnguloDesdeMouse(e.getX(), e.getY(), true);
    }

    private void actualizarRadioYAnguloDesdeMouse(int mouseX, int mouseY, boolean guardarEnHistorial) {
        int centroX = getWidth() / 2;
        int centroY = getHeight() / 2;

        anguloRadianes = Math.atan2(mouseY - centroY, mouseX - centroX);

        double distanciaPixeles = Math.sqrt(Math.pow(mouseX - centroX, 2) + Math.pow(mouseY - centroY, 2));
        double escala = 20.0;
        double nuevoRadio = distanciaPixeles / escala;

        if (nuevoRadio < 0.5) nuevoRadio = 0.5;
        if (nuevoRadio > 15.0) nuevoRadio = 15.0; // Límite máximo

        nuevoRadio = Math.round(nuevoRadio * 100.0) / 100.0;

        this.radio = nuevoRadio;
        repaint();

        if (listener != null) {
            listener.onRadioChanged(nuevoRadio);
            if (guardarEnHistorial) {
                listener.onArrastreFinalizado(); // Se ejecuta únicamente al soltar el mouse
            }
        }
    }

    @Override public void mouseClicked(java.awt.event.MouseEvent e) {}
    @Override public void mouseEntered(java.awt.event.MouseEvent e) {}
    @Override public void mouseExited(java.awt.event.MouseEvent e) {}
    @Override public void mouseMoved(java.awt.event.MouseEvent e) {}
}