/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.poodemo.ejercicio1;

import com.mycompany.poodemo.ejercicio1.modelo.Rectangulo;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * @author frank
 */
public class VentanaRectangulo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRectangulo.class.getName());
    
    // Modelo para la tabla de registros del rectángulo
    private DefaultTableModel modeloTablaRectangulo;
    
    // Instancia del panel de dibujo dinámico e interactivo
    private PanelCanvasRectangulo canvasRectangulo;

    /**
     * Creates new form VentanaRectangulo
     */
    public VentanaRectangulo() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en pantalla
        
        // Inicializar las columnas de la tabla de historial del rectángulo
        modeloTablaRectangulo = new DefaultTableModel(new String[]{"Base", "Altura", "Unidad", "Área Final", "Paso a Paso"}, 0);
        tblRectangulo.setModel(modeloTablaRectangulo);
        
        // Ajustar el ancho de las columnas
        tblRectangulo.getColumnModel().getColumn(0).setPreferredWidth(70);  // Base
        tblRectangulo.getColumnModel().getColumn(1).setPreferredWidth(70);  // Altura
        tblRectangulo.getColumnModel().getColumn(2).setPreferredWidth(120); // Unidad
        tblRectangulo.getColumnModel().getColumn(3).setPreferredWidth(130); // Área Final
        tblRectangulo.getColumnModel().getColumn(4).setPreferredWidth(270); // Paso a Paso
        
        // Deshabilitar el combo de destino por defecto
        jComboBoxDestino.setEnabled(false);
        
        // Configurar e integrar el panel gráfico interactivo dentro del panel de NetBeans
        canvasRectangulo = new PanelCanvasRectangulo();
        canvasRectangulo.setBackground(Color.WHITE);
        
        // Listener para sincronizar el arrastre del mouse y el guardado en la tabla al soltar
        canvasRectangulo.setOnDimensionChangeListener(new PanelCanvasRectangulo.DimensionChangeListener() {
            @Override
            public void onDimensionChanged(double nuevaBase, double nuevaAltura) {
                txtBase.setText(String.valueOf(nuevaBase));
                txtAltura.setText(String.valueOf(nuevaAltura));
                actualizarCalculoEnVivo(nuevaBase, nuevaAltura);
            }

            @Override
            public void onArrastreFinalizado() {
                // Guarda en la tabla del historial únicamente cuando el usuario suelta el mouse
                btnCalcularRectangulo.doClick(); 
            }
        });
        
        panelGrafico.setLayout(new java.awt.BorderLayout());
        panelGrafico.add(canvasRectangulo, java.awt.BorderLayout.CENTER);
    }

    /**
     * Método auxiliar para calcular y mostrar en tiempo real en la interfaz sin saturar la tabla
     */
    private void actualizarCalculoEnVivo(double base, double altura) {
        try {
            String unidadIngreso = jComboBox1.getSelectedItem().toString();
            Rectangulo rectangulo = new Rectangulo(base, altura, unidadIngreso);
            double areaFinal;
            String unidadFinal;
            
            if (tglConvertir.isSelected()) {
                String unidadDestino = jComboBoxDestino.getSelectedItem().toString();
                areaFinal = rectangulo.convertirAreaA(unidadDestino);
                unidadFinal = unidadDestino;
            } else {
                areaFinal = rectangulo.calcularArea();
                unidadFinal = unidadIngreso;
            }
            
            lblResultadoRectangulo.setText(String.format("Área: %.4f %s²", areaFinal, unidadFinal));
            
            canvasRectangulo.setDimensiones(base, altura);
            String unidadDestinoStr = tglConvertir.isSelected() ? jComboBoxDestino.getSelectedItem().toString() : "";
            canvasRectangulo.setResultadoInfo(areaFinal, unidadFinal, tglConvertir.isSelected(), unidadIngreso, unidadDestinoStr);
        } catch (Exception e) {
            // Ignorar errores menores durante el movimiento fluido del mouse
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        btnCalcularRectangulo = new javax.swing.JButton();
        lblResultadoRectangulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRectangulo = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnVolverMenu = new javax.swing.JButton();
        btnLimpiarTabla = new javax.swing.JButton();
        tglConvertir = new javax.swing.JToggleButton();
        jComboBoxDestino = new javax.swing.JComboBox<>();
        panelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cálculo del Rectángulo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Base:");

        jLabel5.setText("Altura:");

        btnCalcularRectangulo.setText("Calcular Rectángulo");
        btnCalcularRectangulo.addActionListener(this::btnCalcularRectanguloActionPerformed);

        lblResultadoRectangulo.setText("Resultado Rectángulo:");

        tblRectangulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblRectangulo);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milímetros (mm)", "Centímetros (cm)\t", "Decímetros (dm)", "Metros (m)", "Kilómetros (km)" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.addActionListener(this::btnVolverMenuActionPerformed);

        btnLimpiarTabla.setText("Limpiar Historial");
        btnLimpiarTabla.addActionListener(this::btnLimpiarTablaActionPerformed);

        tglConvertir.setText("Habilitar Conversión\"");
        tglConvertir.addActionListener(this::tglConvertirActionPerformed);

        jComboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Milímetros (mm)", "Centímetros (cm)", "Decímetros (dm)", "Metros (m)", "Kilómetros (km)" }));
        jComboBoxDestino.addActionListener(this::jComboBoxDestinoActionPerformed);

        panelGrafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelGrafico.setPreferredSize(new java.awt.Dimension(250, 100));

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel3))
                            .addComponent(btnCalcularRectangulo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tglConvertir)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(74, 74, 74)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(panelGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultadoRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnVolverMenu)
                        .addGap(28, 28, 28)
                        .addComponent(btnLimpiarTabla)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglConvertir))
                        .addGap(39, 39, 39)
                        .addComponent(jComboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(panelGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularRectangulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultadoRectangulo)
                    .addComponent(btnVolverMenu)
                    .addComponent(btnLimpiarTabla))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRectanguloActionPerformed
try {
            if (txtBase.getText().trim().isEmpty() || txtAltura.getText().trim().isEmpty()) {
                throw new IllegalArgumentException("Los campos de base y altura no pueden estar vacíos.");
            }
            
            double base = Double.parseDouble(txtBase.getText().trim());
            double altura = Double.parseDouble(txtAltura.getText().trim());
            
            if (base <= 0 || altura <= 0) {
                throw new ArithmeticException("La base y la altura deben ser mayores a 0.");
            }
            
            String unidadIngreso = jComboBox1.getSelectedItem().toString();
            Rectangulo rectangulo = new Rectangulo(base, altura, unidadIngreso);
            
            double areaFinal;
            String unidadFinal;
            String pasoAPaso;
            
            if (tglConvertir.isSelected()) {
                String unidadDestino = jComboBoxDestino.getSelectedItem().toString();
                areaFinal = rectangulo.convertirAreaA(unidadDestino);
                unidadFinal = unidadDestino;
                
                double factor = obtenerFactorPrueba(unidadIngreso) / obtenerFactorPrueba(unidadDestino);
                double baseConv = base * factor;
                double alturaConv = altura * factor;
                pasoAPaso = String.format("Conv. (%.1f y %.1f %s a %s) -> %.2f × %.2f = %.4f", 
                        base, altura, unidadIngreso, unidadDestino, baseConv, alturaConv, areaFinal);
            } else {
                areaFinal = rectangulo.calcularArea();
                unidadFinal = unidadIngreso;
                pasoAPaso = String.format("%.2f × %.2f = %.4f", base, altura, areaFinal);
            }
            
            lblResultadoRectangulo.setText(String.format("Área: %.4f %s²", areaFinal, unidadFinal));
            
            // Añade al historial de la tabla una sola vez
            modeloTablaRectangulo.addRow(new Object[]{base, altura, unidadIngreso, String.format("%.4f %s²", areaFinal, unidadFinal), pasoAPaso});
            
            canvasRectangulo.setDimensiones(base, altura);
            String unidadDestinoStr = tglConvertir.isSelected() ? jComboBoxDestino.getSelectedItem().toString() : "";
            canvasRectangulo.setResultadoInfo(areaFinal, unidadFinal, tglConvertir.isSelected(), unidadIngreso, unidadDestinoStr);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese solo valores numéricos válidos.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Validación", JOptionPane.ERROR_MESSAGE);
        }
    }
        private void txtBaseActionPerformed(java.awt.event.ActionEvent evt) {                                        
        btnCalcularRectangulo.doClick();
    }                                       

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        btnCalcularRectangulo.doClick();
    }
// Método auxiliar rápido para calcular los lados convertidos en el texto del paso a paso
private double obtenerFactorPrueba(String unidad) {
if (unidad.contains("Milímetros")) return 0.001;
        if (unidad.contains("Centímetros")) return 0.01;
        if (unidad.contains("Decímetros")) return 0.1;
        if (unidad.contains("Metros")) return 1.0;
        if (unidad.contains("Kilómetros")) return 1000.0;
        return 1.0;
    }//GEN-LAST:event_btnCalcularRectanguloActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
try {
            if (!txtBase.getText().trim().isEmpty() && !txtAltura.getText().trim().isEmpty()) {
                double base = Double.parseDouble(txtBase.getText().trim());
                double altura = Double.parseDouble(txtAltura.getText().trim());
                actualizarCalculoEnVivo(base, altura);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
VentanaPrincipio menu = new VentanaPrincipio();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        // Método para vaciar el historial de la tabla
        modeloTablaRectangulo.setRowCount(0);
        lblResultadoRectangulo.setText("Resultado Rectángulo:");    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    private void tglConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglConvertirActionPerformed
boolean activar = tglConvertir.isSelected();
        jComboBoxDestino.setEnabled(activar);
        
        if (activar) {
            tglConvertir.setText("Ocultar Conversión");
        } else {
            tglConvertir.setText("Habilitar Conversión");
        }    }//GEN-LAST:event_tglConvertirActionPerformed

    private void jComboBoxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDestinoActionPerformed
try {
            if (!txtBase.getText().trim().isEmpty() && !txtAltura.getText().trim().isEmpty()) {
                double base = Double.parseDouble(txtBase.getText().trim());
                double altura = Double.parseDouble(txtAltura.getText().trim());
                actualizarCalculoEnVivo(base, altura);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_jComboBoxDestinoActionPerformed
                                      
    // Evento del botón Rectángulo

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VentanaRectangulo().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularRectangulo;
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxDestino;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblResultadoRectangulo;
    private javax.swing.JPanel panelGrafico;
    private javax.swing.JTable tblRectangulo;
    private javax.swing.JToggleButton tglConvertir;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtBase;
    // End of variables declaration//GEN-END:variables
}
// =====================================================================
// CLASE AUXILIAR: PANEL GRÁFICO INTERACTIVO PARA RECTÁNGULO (ESTILO GEOGEBRA)
// =====================================================================
class PanelCanvasRectangulo extends JPanel implements java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
    private double base = 0;
    private double altura = 0;
    private String textoResultado = "";
    
    public interface DimensionChangeListener {
        void onDimensionChanged(double nuevaBase, double nuevaAltura);
        void onArrastreFinalizado(); // Se dispara únicamente al soltar el mouse
    }
    
    private DimensionChangeListener listener;

    public void setOnDimensionChangeListener(DimensionChangeListener listener) {
        this.listener = listener;
    }

    public PanelCanvasRectangulo() {
        addMouseListener(this);
        addMouseMotionListener(this);
    }

    public void setDimensiones(double base, double altura) {
        this.base = base;
        this.altura = altura;
        repaint(); 
    }

    public void setResultadoInfo(double area, String unidadFinal, boolean esConvertido, String unidadIngreso, String unidadDestino) {
        if (esConvertido) {
            this.textoResultado = String.format("Área: %.4f %s² (Conv: %s ➔ %s)", area, unidadFinal, unidadIngreso, unidadDestino);
        } else {
            this.textoResultado = String.format("Área: %.4f %s² (Sin conversión)", area, unidadFinal);
        }
        repaint();
    }

    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        
        java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
        g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        int anchoPanel = getWidth();
        int altoPanel = getHeight();
        int centroX = anchoPanel / 2;
        int centroY = altoPanel / 2;

        if (base <= 0 || altura <= 0) {
            g2d.setColor(Color.GRAY);
            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 12));
            g2d.drawString("Haz clic y arrastra para escalar el rectángulo...", 15, 30);
            return;
        }

        double escala = 15.0; 
        int rectAnchoPixeles = (int) (base * escala);
        int rectAltoPixeles = (int) (altura * escala);

        int maxAncho = anchoPanel - 60;
        int maxAlto = altoPanel - 60;
        if (rectAnchoPixeles > maxAncho) rectAnchoPixeles = Math.max(maxAncho, 40);
        if (rectAltoPixeles > maxAlto) rectAltoPixeles = Math.max(maxAlto, 40);

        int xInicio = centroX - (rectAnchoPixeles / 2);
        int yInicio = centroY - (rectAltoPixeles / 2);

        // 1. Relleno del rectángulo (Celeste claro estilo GeoGebra)
        g2d.setColor(new Color(230, 240, 255));
        g2d.fillRect(xInicio, yInicio, rectAnchoPixeles, rectAltoPixeles);

        // 2. Borde del rectángulo
        g2d.setColor(new Color(50, 100, 220));
        g2d.setStroke(new java.awt.BasicStroke(2));
        g2d.drawRect(xInicio, yInicio, rectAnchoPixeles, rectAltoPixeles);

        // 3. Vértices y etiquetas de esquinas (A, B, C, D)
        g2d.setColor(Color.BLACK);
        g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        g2d.fillOval(xInicio - 3, yInicio - 3, 6, 6);
        g2d.drawString("A", xInicio - 15, yInicio - 5);

        g2d.fillOval(xInicio + rectAnchoPixeles - 3, yInicio - 3, 6, 6);
        g2d.drawString("B", xInicio + rectAnchoPixeles + 8, yInicio - 5);

        g2d.fillOval(xInicio + rectAnchoPixeles - 3, yInicio + rectAltoPixeles - 3, 6, 6);
        g2d.drawString("C", xInicio + rectAnchoPixeles + 8, yInicio + rectAltoPixeles + 15);

        g2d.fillOval(xInicio - 3, yInicio + rectAltoPixeles - 3, 6, 6);
        g2d.drawString("D", xInicio - 15, yInicio + rectAltoPixeles + 15);

        // 4. Textos de dimensiones en los lados
        g2d.setColor(new Color(0, 50, 150));
        g2d.drawString("b = " + String.format("%.2f", base), xInicio + (rectAnchoPixeles / 2) - 20, yInicio - 8);
        g2d.drawString("h = " + String.format("%.2f", altura), xInicio + rectAnchoPixeles + 8, yInicio + (rectAltoPixeles / 2) + 5);

        // 5. Mostrar el resultado y estado de conversión dentro de la imagen
        if (!textoResultado.isEmpty()) {
            g2d.setColor(new Color(20, 20, 20));
            g2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
            g2d.drawString(textoResultado, 15, 25);
        }
    }

    @Override
    public void mousePressed(java.awt.event.MouseEvent e) {
        actualizarDimensionesDesdeMouse(e.getX(), e.getY(), false);
    }

    @Override
    public void mouseDragged(java.awt.event.MouseEvent e) {
        actualizarDimensionesDesdeMouse(e.getX(), e.getY(), false);
    }

    @Override
    public void mouseReleased(java.awt.event.MouseEvent e) {
        actualizarDimensionesDesdeMouse(e.getX(), e.getY(), true);
    }

    private void actualizarDimensionesDesdeMouse(int mouseX, int mouseY, boolean guardarEnHistorial) {
        int centroX = getWidth() / 2;
        int centroY = getHeight() / 2;
        
        double distanciaX = Math.abs(mouseX - centroX) * 2;
        double distanciaY = Math.abs(mouseY - centroY) * 2;
        
        double escala = 15.0;
        double nuevaBase = distanciaX / escala;
        double nuevaAltura = distanciaY / escala;
        
        if (nuevaBase < 1.0) nuevaBase = 1.0;
        if (nuevaBase > 15.0) nuevaBase = 15.0;
        
        if (nuevaAltura < 1.0) nuevaAltura = 1.0;
        if (nuevaAltura > 15.0) nuevaAltura = 15.0;
        
        nuevaBase = Math.round(nuevaBase * 100.0) / 100.0;
        nuevaAltura = Math.round(nuevaAltura * 100.0) / 100.0;
        
        this.base = nuevaBase;
        this.altura = nuevaAltura;
        repaint();
        
        if (listener != null) {
            listener.onDimensionChanged(nuevaBase, nuevaAltura);
            if (guardarEnHistorial) {
                listener.onArrastreFinalizado();
            }
        }
    }

    @Override public void mouseClicked(java.awt.event.MouseEvent e) {}
    @Override public void mouseEntered(java.awt.event.MouseEvent e) {}
    @Override public void mouseExited(java.awt.event.MouseEvent e) {}
    @Override public void mouseMoved(java.awt.event.MouseEvent e) {}
}
